steps:
    # build the container image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
              ".",
          ]
      # push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "push",
              "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
          ]
      # Deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "beta",
              "run",
              "deploy",
              "--allow-unauthenticated",
              "$_SERVICE_NAME",
              "--image",
              "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
              "--region",
              "us-central1",
              "--platform",
              "managed",
              "--memory",
              "256Mi",
              "--update-env-vars",
              "APP_DEBUG=${_APP_DEBUG}",
          ]
images:
    - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
    substitution_option: "ALLOW_LOOSE"

substitutions:
    _APP_DEBUG: "true"
